title: TextMiningGUI
description: >-
  Graphic interface for text analysis, implement a few methods such as biplots, correspondece analysis, co-occurrence, clustering, topic models, correlations and sentiments.
baseurl: "/TextMiningGUI/"
url: "" 
github_username:  c0reyes

theme: minima

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true