title: TextMiningGUI
description: >-
  TextMiningGUI is a graphic interface for text analysis, implement a few methods such as HJ-Biplot, AFC, Co-occurrence, Clustering, Topic Models, Correlations and Sentiments.
baseurl: "/TextMiningGUI/"
url: "" 
github_username:  c0reyes

theme: minima

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true